Add babel-eslint, used by .eslintrc.json
otherwise, running `yarn run lint` fails.

Can't add babel-eslint 9+ because then I get

    Cannot read property 'range' of null
    TypeError: Cannot read property 'range' of null
        at SourceCode.getTokenBefore (/Users/craigbeck/dev/premise-frontend-v3/node_modules/eslint/lib/token-store/index.js:303:18)
        at checkSpacingBefore (/Users/craigbeck/dev/premise-frontend-v3/node_modules/eslint/lib/rules/template-curly-spacing.js:52:42)
        at TemplateElement (/Users/craigbeck/dev/premise-frontend-v3/node_modules/eslint/lib/rules/template-curly-spacing.js:117:17)
        at listeners.(anonymous function).forEach.listener (/Users/craigbeck/dev/premise-frontend-v3/node_modules/eslint/lib/util/safe-emitter.js:45:58)
        at Array.forEach (<anonymous>)
        ...