Container list - fix Cannot read property subscribe of undefined
Introduced in #1903.

Go to Compute > Containers > Providers

```
TypeError: Cannot read property 'subscribe' of undefined
   at new <anonymous> (deploy-provider-controller.self-d357ab1….js:248)
```

(in browser console)

Adding that missing `.angular`