Add direct redux npm dependency, redux 4.0.0 breaks
[Redux 4 is here!](https://github.com/reactjs/redux/releases) and [yarn is broken](https://gist.github.com/bdunne/c58ae9f3c26e6647f29392c6cfba7f2b) :(.

Turns out we only depend on redux indirectly, which means the redux 4.0.0 release broke the webpack build..

    ERROR in /home/bdunne/.gem/ruby/2.4.3/bundler/gems/manageiq-ui-classic-8303c278b9c0/node_modules/redux/index.d.ts
    (19,27): error TS1005: ',' expected.

    (and quite a bit more)

Adding that direct dependency.
Also removed @types/redux, since it has been [deprecated](https://www.npmjs.com/package/@types/redux).