CiProcessing specs - stub user for failing retirement specs
Fixes:

    Failures:
      1) VmOrTemplateController#vm_button_operation should continue to retire a vm
         Failure/Error:
           expect(assigns(:flash_array).first[:message]).to \
             include("Retirement initiated for 1 VM and Instance from the %{product} Database" % {:product => Vmdb::Appliance.PRODUCT_NAME})

           expected "Error during 'retire_now': undefined method `userid' for nil:NilClass" to include "Retirement initiated for 1 VM and Instance from the ManageIQ Database"
         # ./spec/controllers/application_controller/ci_processing_spec.rb:942:in `block (3 levels) in <top (required)>'
      2) ServiceController#vm_button_operation should continue to retire a service and does not render flash message 'xxx does not apply xxx'
         Failure/Error:
           expect(assigns(:flash_array).first[:message]).to \
             include("Retirement initiated for 1 Service from the %{product} Database" % {:product => Vmdb::Appliance.PRODUCT_NAME})

           expected "Error during 'retire_now': undefined method `userid' for nil:NilClass" to include "Retirement initiated for 1 Service from the ManageIQ Database"
         # ./spec/controllers/application_controller/ci_processing_spec.rb:874:in `block (3 levels) in <top (required)>'