Remove nil elements from top_nodes array.
Even when section was skipped in x_get_tree_roots method a nil was being added to top_nodes array that was causing undefined method `new' for nil:NilClass
in /app/presenters/tree_node.rb:9. This fix removes any nil elements from array before trying to build RBAC features tree.

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1533391