Fix spec/views/shared/views/_ownership.html.haml_spec.rb:22
Fixes (in fine):

    shared/views/_ownership the ownership group dropdown includes the no group option
    Failure/Error: - table = view.sub_table ? view.sub_table : view.table

    ActionView::Template::Error:
      undefined method `sub_table' for nil:NilClass
    # ./app/views/layouts/_gtl.html.haml:7:in `_plugins_manageiq_ui_classic_app_views_layouts__gtl_html_haml__2862802952630736067_47037408394020'
    # ./app/views/shared/views/_ownership.html.haml:53:in `_plugins_manageiq_ui_classic_app_views_shared_views__ownership_html_haml___2714520125880809098_47037403024140'
    # ./spec/views/shared/views/_ownership.html.haml_spec.rb:30:in `block (2 levels) in <top (required)>'
    # ./spec/spec_helper.rb:75:in `block (3 levels) in <top (required)>'
    # /home/himdel/manageiq-fine/spec/support/evm_spec_helper.rb:34:in `clear_caches'
    # ./spec/spec_helper.rb:75:in `block (2 levels) in <top (required)>'
    # ------------------
    # --- Caused by: ---
    # NoMethodError:
    #   undefined method `sub_table' for nil:NilClass
    #   ./app/views/layouts/_gtl.html.haml:7:in `_plugins_manageiq_ui_classic_app_views_layouts__gtl_html_haml__2862802952630736067_47037408394020'

This is a new spec (from #3404), and in master, mocking `render_gtl_outer` works because `layouts/gtl` loads `layouts/angular/gtl`, which just calls `render_gtl_outer`.

In fine, `layouts/gtl` actually does the GTL rendering, so we need to stub the whole template.