Ensure lodash 3 is available via bower
we're still on lodash3, required via bower

but looks like at some point we've lost the explicit bower dependency

and now, something started depending on lodash4, breaking the UI:

angular.self-4d4ad11…a00bb8370c.js:14801 TypeError: _.contains is not a function
    at ToolbarController (toolbar_controller.s…fd6b619fb5f82.js:66)
    at Object.invoke (angular.self-4d4ad11…2a00bb8370c.js:5107)
    at $controllerInit (angular.self-4d4ad11…a00bb8370c.js:11077)
    at nodeLinkFn (angular.self-4d4ad11…2a00bb8370c.js:9940)
    at compositeLinkFn (angular.self-4d4ad11…2a00bb8370c.js:9249)
    at publicLinkFn (angular.self-4d4ad11…2a00bb8370c.js:9114)
    at angular.self-4d4ad11…2a00bb8370c.js:1961
    at Scope.$eval (angular.self-4d4ad11…a00bb8370c.js:18543)
    at Scope.$apply (angular.self-4d4ad11…a00bb8370c.js:18642)
    at bootstrapApply (angular.self-4d4ad11…2a00bb8370c.js:1959)
(anonymous)	@	angular.self-4d4ad11…a00bb8370c.js:14801
miq_application.self…7bff860d22b.js:1223 Uncaught TypeError: _.contains is not a function
    at miqSelectPickerEvent (miq_application.self…7bff860d22b.js:1223)
    at show_list:1841