Handle customization for all provisions
Don't throw an error if `all_dialogs[:customize][:fields]` doesn't exist

```
FATAL -- production: Error caught: [NoMethodError] undefined method `[]=' for nil:NilClass
       manageiq-ui-classic/app/controllers/application_controller/miq_request_methods.rb:42:in `prov_field_changed'
```