Fix database diagnostics tab
This is to fix the following two problems:
1. Traceback when accessing the diagnostics -> database tab:

Error caught: [NoMethodError] undefined method `display_name' for nil:NilClass
vmdb/app/views/layouts/_edit_log_depot_settings.html.erb:17

2. DB depot selection not working. This was caused by @prev_uri_prefix
being erroneously overwritten by log_depot_get_form_vars() method.

https://bugzilla.redhat.com/show_bug.cgi?id=1145800
(transferred from ManageIQ/manageiq@790199a4a2b01b311799fd260d5719cfb247e167)