debug toasts - Fix an error when closing an error message
Closing an error popup triggers `TypeError: $ctrl._close is not a function at close`

Now passing the right function..

Introduced in #6623
(transferred from ManageIQ/manageiq@11e804069fa1596fbbf1ac9124e1028634279f96)