render_exception: use error modal
and updated error modal to be able to handle the format
we no longer show the whole exception_contents layout partial, only the actual error message