babelrc.js - use require().default for babel7 exports
otherwise we'd have to import them

Fixes

    Error: [BABEL] (multiple files): .default is not a valid Plugin property