Merge pull request #7159 from himdel/error-modal-ajax
render_exception: use error modal

(cherry picked from commit 13cb9027965dfd0ad534ae4b3f3c151a8b9136b7)