Jest - fix "SecurityError: localStorage is not available for opaque origins"
with jsDom 11.12, jest stars failing with

    Test suite failed to run

    SecurityError: localStorage is not available for opaque origins

      at Window.get localStorage [as localStorage] (node_modules/jsdom/lib/jsdom/browser/Window.js:257:15)
          at Array.forEach (<anonymous>)

Looks like jsdom is just trying to follow the browser behaviour more closely, and without `testURL` jest defaults to assuming "about:blank"