More package lockdowns for s390x
Newer patch versions of these packages require es-abstract 1.22.1 which is
incompatible with yarn 1.22 on s390x

Error:
[5/5] Building fresh packages...
success Saved lockfile.
Done in 13.91s.
Webpacker is installed 🎉 🍰
Using /root/BUILD/manageiq-gemset-18.0.0/bundler/gems/manageiq-ui-classic-0d6c1f24a104/config/webpacker.yml file for setting up webpack paths
:zeitwerk is the configured autoloader. This patched file should be removed: /root/BUILD/manageiq/lib/extensions/as_dependencies_interlock.rb once support for the classic loader is dropped. Additionally remove all uses of AS::Depedencies.interlock.
** Using session_store: ActionDispatch::Session::MemoryStore
** ManageIQ master, codename: Radjabov
yarn run v1.22.18
$ /root/BUILD/manageiq-gemset-18.0.0/bundler/gems/manageiq-ui-classic-0d6c1f24a104/node_modules/.bin/webpack --config /root/BUILD/manageiq-gemset-18.0.0/bundler/gems/manageiq-ui-classic-0d6c1f24a104/config/webpack/development.js
/root/BUILD/manageiq-gemset-18.0.0/bundler/gems/manageiq-ui-classic-0d6c1f24a104/node_modules/webpack-cli/bin/cli.js:93
				throw err;
				^

Error: Cannot find module 'es-abstract/2023/RequireObjectCoercible'
Require stack:
- /root/BUILD/manageiq-gemset-18.0.0/bundler/gems/manageiq-ui-classic-0d6c1f24a104/node_modules/object.entries/implementation.js
- /root/BUILD/manageiq-gemset-18.0.0/bundler/gems/manageiq-ui-classic-0d6c1f24a104/node_modules/object.entries/index.js
- /root/BUILD/manageiq-gemset-18.0.0/bundler/gems/manageiq-ui-classic-0d6c1f24a104/node_modules/webpack-manifest-plugin/lib/plugin.js
- /root/BUILD/manageiq-gemset-18.0.0/bundler/gems/manageiq-ui-classic-0d6c1f24a104/node_modules/webpack-manifest-plugin/index.js
- /root/BUILD/manageiq-gemset-18.0.0/bundler/gems/manageiq-ui-classic-0d6c1f24a104/config/webpack/shared.js
- /root/BUILD/manageiq-gemset-18.0.0/bundler/gems/manageiq-ui-classic-0d6c1f24a104/config/webpack/development.js
- /root/BUILD/manageiq-gemset-18.0.0/bundler/gems/manageiq-ui-classic-0d6c1f24a104/node_modules/webpack-cli/bin/utils/convert-argv.js
- /root/BUILD/manageiq-gemset-18.0.0/bundler/gems/manageiq-ui-classic-0d6c1f24a104/node_modules/webpack-cli/bin/cli.js
- /root/BUILD/manageiq-gemset-18.0.0/bundler/gems/manageiq-ui-classic-0d6c1f24a104/node_modules/webpack/bin/webpack.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
    at Module._load (node:internal/modules/cjs/loader:922:27)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (/root/BUILD/manageiq-gemset-18.0.0/bundler/gems/manageiq-ui-classic-0d6c1f24a104/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/root/BUILD/manageiq-gemset-18.0.0/bundler/gems/manageiq-ui-classic-0d6c1f24a104/node_modules/object.entries/implementation.js:3:30)
    at Module._compile (/root/BUILD/manageiq-gemset-18.0.0/bundler/gems/manageiq-ui-classic-0d6c1f24a104/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (/root/BUILD/manageiq-gemset-18.0.0/bundler/gems/manageiq-ui-classic-0d6c1f24a104/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/root/BUILD/manageiq-gemset-18.0.0/bundler/gems/manageiq-ui-classic-0d6c1f24a104/node_modules/object.entries/index.js:6:22)
    at Module._compile (/root/BUILD/manageiq-gemset-18.0.0/bundler/gems/manageiq-ui-classic-0d6c1f24a104/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (/root/BUILD/manageiq-gemset-18.0.0/bundler/gems/manageiq-ui-classic-0d6c1f24a104/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/root/BUILD/manageiq-gemset-18.0.0/bundler/gems/manageiq-ui-classic-0d6c1f24a104/node_modules/webpack-manifest-plugin/lib/plugin.js:1:77)
    at Module._compile (/root/BUILD/manageiq-gemset-18.0.0/bundler/gems/manageiq-ui-classic-0d6c1f24a104/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (/root/BUILD/manageiq-gemset-18.0.0/bundler/gems/manageiq-ui-classic-0d6c1f24a104/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/root/BUILD/manageiq-gemset-18.0.0/bundler/gems/manageiq-ui-classic-0d6c1f24a104/node_modules/webpack-manifest-plugin/index.js:1:80)
    at Module._compile (/root/BUILD/manageiq-gemset-18.0.0/bundler/gems/manageiq-ui-classic-0d6c1f24a104/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/root/BUILD/manageiq-gemset-18.0.0/bundler/gems/manageiq-ui-classic-0d6c1f24a104/node_modules/object.entries/implementation.js',
    '/root/BUILD/manageiq-gemset-18.0.0/bundler/gems/manageiq-ui-classic-0d6c1f24a104/node_modules/object.entries/index.js',
    '/root/BUILD/manageiq-gemset-18.0.0/bundler/gems/manageiq-ui-classic-0d6c1f24a104/node_modules/webpack-manifest-plugin/lib/plugin.js',
    '/root/BUILD/manageiq-gemset-18.0.0/bundler/gems/manageiq-ui-classic-0d6c1f24a104/node_modules/webpack-manifest-plugin/index.js',
    '/root/BUILD/manageiq-gemset-18.0.0/bundler/gems/manageiq-ui-classic-0d6c1f24a104/config/webpack/shared.js',
    '/root/BUILD/manageiq-gemset-18.0.0/bundler/gems/manageiq-ui-classic-0d6c1f24a104/config/webpack/development.js',
    '/root/BUILD/manageiq-gemset-18.0.0/bundler/gems/manageiq-ui-classic-0d6c1f24a104/node_modules/webpack-cli/bin/utils/convert-argv.js',
    '/root/BUILD/manageiq-gemset-18.0.0/bundler/gems/manageiq-ui-classic-0d6c1f24a104/node_modules/webpack-cli/bin/cli.js',
    '/root/BUILD/manageiq-gemset-18.0.0/bundler/gems/manageiq-ui-classic-0d6c1f24a104/node_modules/webpack/bin/webpack.js'
  ]
}

Node.js v18.16.1
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[Webpacker] Compilation Failed