Use a shared helper to ensure we open & wait on the enabled accordion
The hope is to resolve the sporadic failure below where the item is still
disabled:

```
1) Overview > Reports Tests
       Can add, edit and delete a schedule:
     CypressError: Timed out retrying after 4050ms: `cy.click()` failed because this element:

          `<li class="list-group-item node-treeview-schedules_tree" data-nodeid="0.0.0">...</li>`

          has CSS `pointer-events: none`, inherited from this element:

`<div class="sidebar-pf sidebar-pf-left scrollable max-height col-sm-4 col-md-3 col-sm-pull-8 col-md-pull-9 sidebar-disabled" id="left_div" style="min-height: 0px;">...</div>`

          `pointer-events: none` prevents user mouse interaction.
```